spring:
  application:
    name: feedback-monitor
  data:
    mongodb:
      uri: mongodb+srv://raeojin:8division2024@cluster0.tyvzi.mongodb.net/feedback-monitor-db?retryWrites=true&w=majority&appName=Cluster0
